CREATE TABLE CLIENT (
    ID_CLIENT   NUMBER PRIMARY KEY,
    NOM         VARCHAR2(50)    NOT NULL,
    PRENOM      VARCHAR2(50)    NOT NULL,
    EMAIL       VARCHAR2(100)   NOT NULL,
    TELEPHONE   VARCHAR2(20)    NOT NULL,
    ADRESSE     VARCHAR2(200)
);

CREATE TABLE COMMANDE (
    ID_COMMANDE    NUMBER PRIMARY KEY,
    DATE_COMMANDE  DATE          NOT NULL,
    MONTANT_TOTAL  NUMBER(10,2)  NOT NULL,
    STATUT         VARCHAR2(30)  NOT NULL,
    MODE_PAIEMENT  VARCHAR2(30)  NOT NULL,
    ID_CLIENT      NUMBER        NOT NULL,
    CONSTRAINT FK_COMMANDE_CLIENT
        FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    CONSTRAINT CHK_MONTANT_POS
        CHECK (MONTANT_TOTAL >= 0)
);
